// AUTO-GENERATED from docs/State_Licensing_and_Issues_Matrix.xlsx (Issues Matrix tab).
// Do not edit by hand — regenerate with `npm run gen:issues`.
// Indiana / Porter County scope; planning tool, not legal advice.

import type { MatrixIssue } from "./issues";

export const ISSUES_DATA: MatrixIssue[] = [
  {
    rank: 1, category: "Recurring / Subscription", issue: "HVAC filter replacement",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 1,
    symptom: "Quarterly or per-manufacturer interval", notes: "Universal need. The anchor SKU for any membership plan.",
  },
  {
    rank: 2, category: "Recurring / Subscription", issue: "Smoke and CO detector battery and test",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 1,
    symptom: "Annual battery plus function test, all units", notes: "Universal, fast, and a genuine safety service.",
  },
  {
    rank: 3, category: "HVAC", issue: "Dirty or clogged air filter",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.95,
    symptom: "Restricted airflow: weak output, short cycling, frozen coil", notes: "Highest-frequency HVAC issue in existence. Anchor of any subscription plan.",
  },
  {
    rank: 4, category: "Home Maintenance", issue: "Clogged gutters",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Medium (ladder)", recurring: true, likelihood: 0.85,
    symptom: "Overflow, water at foundation, ice damming", notes: "Twice yearly. Cornerstone of a maintenance plan.",
  },
  {
    rank: 5, category: "Recurring / Subscription", issue: "Gutter cleaning",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Medium (ladder)", recurring: true, likelihood: 0.85,
    symptom: "Spring and fall", notes: "Twice yearly, highly predictable, easy to route in batches.",
  },
  {
    rank: 6, category: "Recurring / Subscription", issue: "Outdoor faucet winterization",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.8,
    symptom: "Hose removal, shutoff, freeze prevention", notes: "Seasonal, prevents an expensive burst-pipe claim.",
  },
  {
    rank: 7, category: "Internet", issue: "No internet - modem/router needs reboot",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.7,
    symptom: "Gateway locked up, needs power cycle", notes: "Trivial fix, real perceived value.",
  },
  {
    rank: 8, category: "Recurring / Subscription", issue: "Refrigerator water filter change",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.7,
    symptom: "Every 6 months per manufacturer", notes: "Trivial labor, recurring parts margin.",
  },
  {
    rank: 9, category: "Plumbing", issue: "Clogged toilet",
    scope: "in_scope", hardStop: false, license: "None in practice",
    risk: "Low", recurring: false, likelihood: 0.65,
    symptom: "Bowl won't drain or overflows", notes: "Plunger / closet auger. Zero enforcement risk.",
  },
  {
    rank: 10, category: "Recurring / Subscription", issue: "Water softener salt refill",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.65,
    symptom: "Monthly to quarterly depending on hardness", notes: "Heavy bags customers hate carrying. Strong subscription fit in hard-water NW Indiana.",
  },
  {
    rank: 11, category: "Electrical", issue: "Chirping smoke or CO detector",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.6,
    symptom: "Low battery, or end-of-life sealed unit", notes: "Battery units fully yours. High gratitude, low effort.",
  },
  {
    rank: 12, category: "Recurring / Subscription", issue: "Dryer vent cleaning",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Medium (fire)", recurring: true, likelihood: 0.6,
    symptom: "Annual; more often for large households", notes: "Fire prevention. Best margin-to-effort ratio on this list.",
  },
  {
    rank: 13, category: "Electrical", issue: "Tripped breaker",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.55,
    symptom: "Circuit dead; breaker in middle or off position", notes: "Reset once. A second trip is a fault - stop.",
  },
  {
    rank: 14, category: "Home Maintenance", issue: "Interior paint scuffs and touch-up",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.55,
    symptom: "Wear in hallways, stairwells, kids' rooms", notes: "Easy filler work between service calls.",
  },
  {
    rank: 15, category: "Internet", issue: "Slow speeds",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.55,
    symptom: "Not getting the speeds being paid for", notes: "Wired test at the gateway isolates ISP from Wi-Fi.",
  },
  {
    rank: 16, category: "Plumbing", issue: "Slow tub or shower drain",
    scope: "in_scope", hardStop: false, license: "Grey - low risk",
    risk: "Low", recurring: false, likelihood: 0.55,
    symptom: "Hair buildup at the strainer or trap", notes: "Hand snake through the opening. Non-pressurized.",
  },
  {
    rank: 17, category: "Recurring / Subscription", issue: "Condensate line flush",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.55,
    symptom: "Annual, before cooling season", notes: "Prevents the single most common summer AC failure.",
  },
  {
    rank: 18, category: "Recurring / Subscription", issue: "Condenser coil cleaning",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.55,
    symptom: "Annual, spring", notes: "Pairs naturally with the condensate flush as a spring visit.",
  },
  {
    rank: 19, category: "Electrical", issue: "Tripped GFCI (including upstream device)",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.5,
    symptom: "Outlets dead; controlling GFCI is in another room", notes: "Bathroom GFCI often feeds garage and exterior. Huge share of 'dead outlet' calls.",
  },
  {
    rank: 20, category: "Home Maintenance", issue: "Bathroom caulk failure at tub or shower",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.5,
    symptom: "Cracked, moldy, or missing caulk bead", notes: "Prevents real water damage. Natural annual inspection item.",
  },
  {
    rank: 21, category: "Internet", issue: "Wi-Fi dead zones",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.5,
    symptom: "No signal in bedrooms, basement, or garage", notes: "Site survey and router relocation. High-margin.",
  },
  {
    rank: 22, category: "Plumbing", issue: "Slow bathroom sink drain",
    scope: "in_scope", hardStop: false, license: "Grey - low risk",
    risk: "Low", recurring: false, likelihood: 0.5,
    symptom: "Hair and soap on the pop-up assembly", notes: "Same as above.",
  },
  {
    rank: 23, category: "Recurring / Subscription", issue: "Dishwasher filter cleaning",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.5,
    symptom: "Quarterly", notes: "Most owners don't know the filter exists.",
  },
  {
    rank: 24, category: "Recurring / Subscription", issue: "Sump pump test",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Medium", recurring: true, likelihood: 0.5,
    symptom: "Semiannual; critical before spring thaw", notes: "Porter County basements make this an easy sell.",
  },
  {
    rank: 25, category: "Home Maintenance", issue: "Door won't latch",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.45,
    symptom: "Strike plate misaligned from settling or humidity", notes: "Five-minute fix, very high satisfaction.",
  },
  {
    rank: 26, category: "Home Maintenance", issue: "Squeaky door hinges",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.45,
    symptom: "Dry or worn hinge pins", notes: "Trivial add-on to any visit.",
  },
  {
    rank: 27, category: "Plumbing", issue: "Running or phantom-flushing toilet",
    scope: "grey", hardStop: false, license: "State Plumbing (grey)",
    risk: "Low", recurring: false, likelihood: 0.45,
    symptom: "Failed flapper or fill valve", notes: "Diagnosis safe. Get counsel's read before replacing parts.",
  },
  {
    rank: 28, category: "Recurring / Subscription", issue: "Range hood filter cleaning or replacement",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.45,
    symptom: "Quarterly", notes: "Fast add-on during any kitchen visit.",
  },
  {
    rank: 29, category: "Home Maintenance", issue: "Drywall nail pops and small holes",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.42,
    symptom: "Seasonal movement, furniture damage, removed fixtures", notes: "Patch, sand, touch-up. Core handyman work.",
  },
  {
    rank: 30, category: "Appliances", issue: "Garbage disposal jammed or humming",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.4,
    symptom: "Foreign object binding the impeller", notes: "Hex key from below plus reset button. Two minutes.",
  },
  {
    rank: 31, category: "HVAC", issue: "Clogged condensate drain line",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.4,
    symptom: "Full pan trips float switch; AC stops silently in summer", notes: "Top summer no-cool call. Annual flush prevents it entirely.",
  },
  {
    rank: 32, category: "Home Maintenance", issue: "Mildew in bathroom",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.4,
    symptom: "Poor ventilation, inadequate exhaust run time", notes: "Often solved by fixing the exhaust fan or adding a timer.",
  },
  {
    rank: 33, category: "Internet", issue: "Streaming buffering",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.4,
    symptom: "Bandwidth saturation, DNS, or QoS misconfiguration", notes: "Fully yours.",
  },
  {
    rank: 34, category: "Plumbing", issue: "Dripping faucet",
    scope: "out_of_scope", hardStop: false, license: "State Plumbing",
    risk: "Low", recurring: false, likelihood: 0.4,
    symptom: "Worn cartridge, washer, or O-ring", notes: "Pressurized supply side. Diagnose and refer.",
  },
  {
    rank: 35, category: "Recurring / Subscription", issue: "Furnace humidifier pad replacement",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.4,
    symptom: "Annual, before heating season", notes: "Bundles with the fall filter change.",
  },
  {
    rank: 36, category: "Appliances", issue: "Dishwasher not draining",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.38,
    symptom: "Clogged filter, kinked hose, blocked air gap", notes: "Check for a disposal knockout plug never removed.",
  },
  {
    rank: 37, category: "Home Maintenance", issue: "Cabinet door misaligned or loose hinge",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.38,
    symptom: "Sagging door, won't close flush", notes: "Adjustment takes minutes.",
  },
  {
    rank: 38, category: "Electrical", issue: "Flickering or buzzing LED bulbs",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.35,
    symptom: "Non-dimmable bulb on a dimmer, or incompatible dimmer", notes: "Bulb swap is yours. Dimmer replacement is not.",
  },
  {
    rank: 39, category: "HVAC", issue: "Condenser coil blocked by debris",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.35,
    symptom: "Leaves, grass, cottonwood, shrubs grown in too close", notes: "Rinse coil, clear 2 ft. Natural spring tune-up item.",
  },
  {
    rank: 40, category: "HVAC", issue: "Thermostat batteries dead",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.35,
    symptom: "Blank display, system unresponsive", notes: "Two-minute fix people routinely call a contractor for.",
  },
  {
    rank: 41, category: "Home Maintenance", issue: "Bathroom exhaust fan noisy or weak",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.35,
    symptom: "Dust-clogged blower, disconnected duct in attic", notes: "Ties directly to the mildew complaint.",
  },
  {
    rank: 42, category: "Home Maintenance", issue: "Furniture assembly, TV mounting, shelving",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.35,
    symptom: "Flat-pack builds, wall mounts, closet systems", notes: "Pure revenue, zero regulatory exposure.",
  },
  {
    rank: 43, category: "Internet", issue: "Smart device won't connect to Wi-Fi",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.35,
    symptom: "Device needs 2.4 GHz; band steering blocking it", notes: "Very common with cameras, plugs, thermostats.",
  },
  {
    rank: 44, category: "Plumbing", issue: "Clogged aerator or showerhead",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.35,
    symptom: "Mineral scale reducing flow", notes: "Unscrew, descale, reinstall. Natural recurring item in hard-water areas.",
  },
  {
    rank: 45, category: "Recurring / Subscription", issue: "Bathroom exhaust fan cleaning",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.35,
    symptom: "Annual", notes: "Prevents the mildew complaints above.",
  },
  {
    rank: 46, category: "Recurring / Subscription", issue: "Garage door lubrication and balance check",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Medium", recurring: true, likelihood: 0.35,
    symptom: "Annual", notes: "Inspect only - never adjust springs.",
  },
  {
    rank: 47, category: "Recurring / Subscription", issue: "Refrigerator coil cleaning",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.35,
    symptom: "Annual", notes: "Extends appliance life measurably. Easy to justify.",
  },
  {
    rank: 48, category: "Recurring / Subscription", issue: "Whole-house water filter cartridge change",
    scope: "grey", hardStop: false, license: "Grey - plumbed inline",
    risk: "Low", recurring: true, likelihood: 0.35,
    symptom: "Every 3 to 6 months", notes: "Cartridge swap on an existing housing. Installing the system is plumbing.",
  },
  {
    rank: 49, category: "Home Maintenance", issue: "Window screen torn",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.32,
    symptom: "Pets, storms, general age", notes: "Re-screening is cheap and easy to batch.",
  },
  {
    rank: 50, category: "Appliances", issue: "Dryer not drying (clogged vent)",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Medium (fire)", recurring: true, likelihood: 0.3,
    symptom: "Long cycles, hot laundry room, lint at exterior hood", notes: "Genuine fire-hazard fix. Best recurring service on the list.",
  },
  {
    rank: 51, category: "Appliances", issue: "Refrigerator not cooling",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.3,
    symptom: "Condenser coils packed with dust and pet hair", notes: "Coil cleaning solves a large share. High margin.",
  },
  {
    rank: 52, category: "Electrical", issue: "Overloaded circuit",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.3,
    symptom: "Space heater plus microwave on one 15A circuit", notes: "Advisory only. Zero risk, real value.",
  },
  {
    rank: 53, category: "HVAC", issue: "Blocked or closed supply registers / returns",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.3,
    symptom: "Furniture over returns, dampers left in seasonal position", notes: "Explains most room-to-room temperature complaints.",
  },
  {
    rank: 54, category: "HVAC", issue: "Thermostat set wrong (mode/schedule)",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.3,
    symptom: "Heat vs cool, fan AUTO vs ON, schedule overriding manual", notes: "Pure education. Photograph settings before changing.",
  },
  {
    rank: 55, category: "Home Maintenance", issue: "Sticking door or window",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.3,
    symptom: "Humidity swelling, settling, paint buildup", notes: "Plane, adjust, or lubricate.",
  },
  {
    rank: 56, category: "Home Maintenance", issue: "Weatherstripping worn on exterior door",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.3,
    symptom: "Visible daylight, drafts, higher bills", notes: "Natural fall inspection item.",
  },
  {
    rank: 57, category: "Internet", issue: "ISP outage vs local fault",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.3,
    symptom: "Nothing works; unclear whose problem it is", notes: "Isolating this saves a wasted provider appointment.",
  },
  {
    rank: 58, category: "Smart Home & Security", issue: "Doorbell camera won't connect to Wi-Fi",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.3,
    symptom: "Weak signal at the door, or 2.4 GHz band issue", notes: "Extremely common. Fully yours.",
  },
  {
    rank: 59, category: "Appliances", issue: "Dishwasher not cleaning dishes",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.28,
    symptom: "Clogged spray arms, low inlet temp, wrong detergent", notes: "Fully yours end to end.",
  },
  {
    rank: 60, category: "Appliances", issue: "Washer won't drain",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.28,
    symptom: "Coin trap / drain pump filter clogged", notes: "A sock or coin in the pump filter is extremely common.",
  },
  {
    rank: 61, category: "Electrical", issue: "Light fixture failure / replacement",
    scope: "out_of_scope", hardStop: false, license: "Local Electrical",
    risk: "Low", recurring: false, likelihood: 0.28,
    symptom: "Fixture dead or being upgraded", notes: "Line-voltage fixture work is licensed.",
  },
  {
    rank: 62, category: "Home Maintenance", issue: "Garage door won't close",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.28,
    symptom: "Photo eye misaligned or obstructed", notes: "Usually a 60-second realignment.",
  },
  {
    rank: 63, category: "Home Maintenance", issue: "Grout cracking or missing in tile",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.28,
    symptom: "Movement, age, moisture", notes: "Regrout and seal.",
  },
  {
    rank: 64, category: "Home Maintenance", issue: "Loose towel bar, grab bar, or accessory",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.28,
    symptom: "Failed drywall anchors", notes: "Grab bars especially - anchor into blocking, not drywall.",
  },
  {
    rank: 65, category: "Smart Home & Security", issue: "Smart bulbs or plugs unresponsive",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.28,
    symptom: "Lost pairing, firmware update, hub offline", notes: "Fully yours.",
  },
  {
    rank: 66, category: "Home Maintenance", issue: "Loose or damaged downspout",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.26,
    symptom: "Separated at seam, discharging at foundation", notes: "Pairs with every gutter cleaning.",
  },
  {
    rank: 67, category: "Smart Home & Security", issue: "Security camera offline",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.26,
    symptom: "Wi-Fi drop, power loss, firmware issue", notes: "Fully yours.",
  },
  {
    rank: 68, category: "Appliances", issue: "Appliance won't power on",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.25,
    symptom: "Tripped GFCI, unplugged, failed cord or outlet", notes: "Check power before assuming appliance failure.",
  },
  {
    rank: 69, category: "Appliances", issue: "Ice maker not producing",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.25,
    symptom: "Frozen or kinked supply line, arm up, clogged screen", notes: "Mostly a water-supply diagnosis.",
  },
  {
    rank: 70, category: "HVAC", issue: "Tripped condensate float safety switch",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.25,
    symptom: "System locked out after pan filled", notes: "Clear the cause first, then reset.",
  },
  {
    rank: 71, category: "Home Maintenance", issue: "Squeaky floor",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.25,
    symptom: "Subfloor separation from joists", notes: "Screws from below where accessible.",
  },
  {
    rank: 72, category: "Internet", issue: "Mesh system setup or bad node placement",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.25,
    symptom: "Nodes too far apart or clustered in one room", notes: "Most self-installs put nodes in the wrong places.",
  },
  {
    rank: 73, category: "Phone", issue: "Smartphone settings problems for seniors",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.25,
    symptom: "Ringer muted, Do Not Disturb stuck on, contacts lost", notes: "Not glamorous, but drives referrals in this demographic.",
  },
  {
    rank: 74, category: "Recurring / Subscription", issue: "Caulk inspection and refresh",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.25,
    symptom: "Annual, wet areas and exterior", notes: "Cheap prevention against expensive water damage.",
  },
  {
    rank: 75, category: "Recurring / Subscription", issue: "Irrigation blowout and spring startup",
    scope: "partial", hardStop: false, license: "Backflow device may be regulated",
    risk: "Low", recurring: true, likelihood: 0.25,
    symptom: "Seasonal, twice yearly", notes: "Verify Indiana backflow tester requirements before touching the device.",
  },
  {
    rank: 76, category: "Recurring / Subscription", issue: "Under-sink RO filter change",
    scope: "grey", hardStop: false, license: "Grey - plumbed inline",
    risk: "Low", recurring: true, likelihood: 0.25,
    symptom: "Every 6 to 12 months", notes: "Same grey zone as the whole-house filter.",
  },
  {
    rank: 77, category: "Recurring / Subscription", issue: "Weatherstripping and draft inspection",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.25,
    symptom: "Annual, fall", notes: "Natural fall visit component.",
  },
  {
    rank: 78, category: "Recurring / Subscription", issue: "Whole-home safety and systems audit",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.25,
    symptom: "Annual walkthrough with a written report", notes: "Your highest-value recurring product - and it generates repair leads.",
  },
  {
    rank: 79, category: "Smart Home & Security", issue: "Smart lock battery dead",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.25,
    symptom: "Batteries drained faster than expected", notes: "Natural recurring check item.",
  },
  {
    rank: 80, category: "Home Maintenance", issue: "Cabinet drawer slide broken",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.24,
    symptom: "Drawer drags, falls, or won't close", notes: "Straightforward parts replacement.",
  },
  {
    rank: 81, category: "Home Maintenance", issue: "Exterior caulk failure at windows and trim",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.24,
    symptom: "Gaps allowing water and air intrusion", notes: "Annual exterior inspection item.",
  },
  {
    rank: 82, category: "Smart Home & Security", issue: "Automations or routines broken after app update",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.24,
    symptom: "Scenes stopped firing, schedules lost", notes: "Fully yours. Recurring by nature - apps update constantly.",
  },
  {
    rank: 83, category: "Appliances", issue: "Washer won't spin",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.22,
    symptom: "Unbalanced load, failed lid switch", notes: "Fully yours.",
  },
  {
    rank: 84, category: "Electrical", issue: "Dead outlet (device failure)",
    scope: "out_of_scope", hardStop: false, license: "Local Electrical",
    risk: "Medium", recurring: false, likelihood: 0.22,
    symptom: "No power at receptacle, upstream OK", notes: "Test at the face only. Replacement is licensed.",
  },
  {
    rank: 85, category: "Home Maintenance", issue: "Garage door opener remote or keypad dead",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.22,
    symptom: "Battery, reprogramming after power loss", notes: "Easy win.",
  },
  {
    rank: 86, category: "Home Maintenance", issue: "Wasp, hornet, or bee nest",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Medium", recurring: false, likelihood: 0.22,
    symptom: "Nest at eave, deck, or entry", notes: "Check whether Indiana pesticide rules apply to for-hire application.",
  },
  {
    rank: 87, category: "Home Maintenance", issue: "Water stain on ceiling",
    scope: "partial", hardStop: false, license: "None to diagnose",
    risk: "Medium", recurring: false, likelihood: 0.22,
    symptom: "Roof leak, plumbing leak, or condensation", notes: "Diagnosis is the valuable part. Source determines who fixes it.",
  },
  {
    rank: 88, category: "Smart Home & Security", issue: "Voice assistant not recognizing devices",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.22,
    symptom: "Device names, room assignments, account linking", notes: "Fully yours.",
  },
  {
    rank: 89, category: "Appliances", issue: "Oven not reaching temperature",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.2,
    symptom: "Calibration drift or failed bake element", notes: "Also confirm a 240V range hasn't lost one leg.",
  },
  {
    rank: 90, category: "Electrical", issue: "Failed light switch",
    scope: "out_of_scope", hardStop: false, license: "Local Electrical",
    risk: "Low", recurring: false, likelihood: 0.2,
    symptom: "Switch does nothing or is intermittent", notes: "Device replacement is licensed in most jurisdictions.",
  },
  {
    rank: 91, category: "HVAC", issue: "Tripped breaker or pulled disconnect at unit",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.2,
    symptom: "No power to air handler or condenser", notes: "Reset once. Repeat trips mean an electrical fault - hand off.",
  },
  {
    rank: 92, category: "Home Maintenance", issue: "Bifold or sliding closet door off track",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.2,
    symptom: "Bent track, worn rollers, misaligned pivot", notes: "Extremely common, five-minute fix, near-zero parts cost.",
  },
  {
    rank: 93, category: "Home Maintenance", issue: "Deck board loose, split, or rotted",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Medium", recurring: false, likelihood: 0.2,
    symptom: "Age, weather, fastener failure", notes: "Confirm whether the scope triggers a local permit.",
  },
  {
    rank: 94, category: "Home Maintenance", issue: "Loose stair railing or handrail",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Medium (fall)", recurring: false, likelihood: 0.2,
    symptom: "Failed anchors, loose balusters", notes: "Real safety item. Anchor into structure.",
  },
  {
    rank: 95, category: "Home Maintenance", issue: "Pest entry points (mice, bats, squirrels)",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.2,
    symptom: "Gaps at soffit, foundation, dryer vent, utility penetrations", notes: "Exclusion work. Confirm whether it triggers Indiana pest-control licensing.",
  },
  {
    rank: 96, category: "Phone", issue: "Cell dead zone in the home",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.2,
    symptom: "Poor carrier coverage indoors", notes: "Wi-Fi calling setup or booster install.",
  },
  {
    rank: 97, category: "Plumbing", issue: "Sewer odor indoors",
    scope: "partial", hardStop: false, license: "None to fill a trap",
    risk: "Low", recurring: false, likelihood: 0.2,
    symptom: "Dry trap in an unused fixture, or vent issue", notes: "Running water to refill a trap solves this surprisingly often.",
  },
  {
    rank: 98, category: "Recurring / Subscription", issue: "Sump backup battery test and replacement",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Medium", recurring: true, likelihood: 0.2,
    symptom: "Annual test, battery every 3 to 5 years", notes: "Pairs with the sump test.",
  },
  {
    rank: 99, category: "Recurring / Subscription", issue: "Water heater flush",
    scope: "grey", hardStop: false, license: "State Plumbing (grey)",
    risk: "Medium", recurring: true, likelihood: 0.2,
    symptom: "Annual, sediment removal", notes: "Commonly done by handymen; strictly it is water-heater maintenance. Get counsel's read.",
  },
  {
    rank: 100, category: "Smart Home & Security", issue: "Camera field of view or mounting angle wrong",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.2,
    symptom: "Covering sky or driveway instead of the door", notes: "Remount and re-aim. Easy, visible value.",
  },
  {
    rank: 101, category: "Smart Home & Security", issue: "Video doorbell chime not ringing indoors",
    scope: "in_scope", hardStop: false, license: "None (low voltage)",
    risk: "Low", recurring: false, likelihood: 0.2,
    symptom: "Chime not configured, or transformer too weak", notes: "Transformer upgrade is low voltage - confirm locally.",
  },
  {
    rank: 102, category: "Appliances", issue: "Refrigerator leaking water inside/out",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.18,
    symptom: "Clogged defrost drain", notes: "Clear the drain tube - classic quick win.",
  },
  {
    rank: 103, category: "Electrical", issue: "Ceiling fan wobble or noise",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.18,
    symptom: "Unbalanced blades, loose downrod or mounting box", notes: "Balancing and tightening fine. Rewiring is not.",
  },
  {
    rank: 104, category: "Electrical", issue: "Unlabeled panel / unknown circuits",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.18,
    symptom: "Homeowner can't find the right breaker", notes: "Circuit mapping is a sellable standalone service, zero exposure.",
  },
  {
    rank: 105, category: "Home Maintenance", issue: "Basement humidity or musty smell",
    scope: "partial", hardStop: false, license: "None",
    risk: "Medium", recurring: false, likelihood: 0.18,
    symptom: "Inadequate dehumidification, poor drainage", notes: "Diagnose and advise. Waterproofing is a specialty referral.",
  },
  {
    rank: 106, category: "Home Maintenance", issue: "Fogged double-pane window",
    scope: "out_of_scope", hardStop: false, license: "None (specialty)",
    risk: "Low", recurring: false, likelihood: 0.18,
    symptom: "Failed insulated glass seal", notes: "Diagnose and refer to a glass specialist. Glass units are not a handyman repair.",
  },
  {
    rank: 107, category: "Home Maintenance", issue: "Loose floor tile or vinyl plank",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.18,
    symptom: "Adhesive failure, subfloor movement", notes: "Small-area repair.",
  },
  {
    rank: 108, category: "Home Maintenance", issue: "Window won't stay open",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.18,
    symptom: "Broken sash balance or spiral balance", notes: "Parts are inexpensive and widely available.",
  },
  {
    rank: 109, category: "Internet", issue: "Router still on default admin password",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.18,
    symptom: "Security exposure; no guest network", notes: "Easy add-on to any network visit.",
  },
  {
    rank: 110, category: "Internet", issue: "Smart home devices dropped after router change",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.18,
    symptom: "New SSID or password broke every device", notes: "Tedious but easy - good billable time.",
  },
  {
    rank: 111, category: "Plumbing", issue: "Leaking P-trap slip nut",
    scope: "grey", hardStop: false, license: "Grey - non-pressurized",
    risk: "Low", recurring: false, likelihood: 0.18,
    symptom: "Drip under the sink, water in the cabinet", notes: "Lowest-risk plumbing repair: gravity drain, reversible.",
  },
  {
    rank: 112, category: "Plumbing", issue: "Low water pressure",
    scope: "partial", hardStop: false, license: "Grey",
    risk: "Low", recurring: false, likelihood: 0.18,
    symptom: "Whole house or single fixture", notes: "Gauge at hose bib, check PRV, isolate fixture vs system.",
  },
  {
    rank: 113, category: "Smart Home & Security", issue: "Alarm sensor battery dead",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.18,
    symptom: "Panel showing low-battery fault", notes: "Recurring by design.",
  },
  {
    rank: 114, category: "Smart Home & Security", issue: "Camera night vision poor or IR glare",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.18,
    symptom: "IR reflecting off glass or a nearby wall", notes: "Repositioning solves nearly all of these.",
  },
  {
    rank: 115, category: "Appliances", issue: "Washer leaking",
    scope: "partial", hardStop: false, license: "None (hose = grey)",
    risk: "Medium", recurring: false, likelihood: 0.16,
    symptom: "Burst supply hose, front-loader door gasket", notes: "Recommend braided steel hoses - real preventive value.",
  },
  {
    rank: 116, category: "Home Maintenance", issue: "Fence gate sagging",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.16,
    symptom: "Post movement, hinge failure, no anti-sag brace", notes: "Anti-sag kit is a fast fix.",
  },
  {
    rank: 117, category: "Home Maintenance", issue: "Missing or damaged shingles",
    scope: "partial", hardStop: false, license: "None state / verify local",
    risk: "High (fall)", recurring: false, likelihood: 0.16,
    symptom: "Wind damage, age, visible from ground", notes: "Diagnose from ground or drone. Roof work needs fall protection and its own insurance.",
  },
  {
    rank: 118, category: "Smart Home & Security", issue: "Camera storage full or SD card failed",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.16,
    symptom: "Recording gaps, card errors", notes: "Card swap and retention settings.",
  },
  {
    rank: 119, category: "Smart Home & Security", issue: "Smart thermostat installation",
    scope: "grey", hardStop: false, license: "None (24V) - verify",
    risk: "Low", recurring: false, likelihood: 0.16,
    symptom: "Homeowner bought one, needs it installed", notes: "Missing C-wire is the usual complication. Low voltage, but at the furnace board.",
  },
  {
    rank: 120, category: "Appliances", issue: "Range hood not venting",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.15,
    symptom: "Grease-clogged filter, disconnected duct, failed fan", notes: "Fully yours. Filter cleaning is a recurring item.",
  },
  {
    rank: 121, category: "Electrical", issue: "Doorbell not working",
    scope: "in_scope", hardStop: false, license: "None (low voltage)",
    risk: "Low", recurring: false, likelihood: 0.15,
    symptom: "Failed transformer, button, or chime", notes: "Low voltage - fully yours including the transformer.",
  },
  {
    rank: 122, category: "HVAC", issue: "Frozen evaporator coil",
    scope: "partial", hardStop: false, license: "None to thaw",
    risk: "Medium", recurring: false, likelihood: 0.15,
    symptom: "Ice on indoor coil or line set", notes: "Thaw plus airflow fix is yours. Refrigerant cause is not.",
  },
  {
    rank: 123, category: "Home Maintenance", issue: "Deck or fence needs sealing",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.15,
    symptom: "Graying, water no longer beading", notes: "Natural annual or biennial recurring job.",
  },
  {
    rank: 124, category: "Home Maintenance", issue: "Dryer vent hood flapper stuck or blocked",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.15,
    symptom: "Lint buildup or bird nest at exterior hood", notes: "Pairs with dryer vent cleaning.",
  },
  {
    rank: 125, category: "Internet", issue: "Extender misconfigured / double NAT",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.15,
    symptom: "Halved bandwidth, devices can't see each other", notes: "Fully yours.",
  },
  {
    rank: 126, category: "Phone", issue: "Cordless handset not working",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.15,
    symptom: "Dead battery pack, handset unregistered from base", notes: "Battery packs are a cheap stocked part.",
  },
  {
    rank: 127, category: "Plumbing", issue: "No hot water",
    scope: "out_of_scope", hardStop: false, license: "State Plumbing / gas",
    risk: "High", recurring: false, likelihood: 0.15,
    symptom: "Failed element, thermostat, pilot, or aged tank", notes: "Diagnose only. Check breaker and setting, then refer.",
  },
  {
    rank: 128, category: "Plumbing", issue: "Sump pump failure",
    scope: "grey", hardStop: false, license: "Grey - plug-in unit",
    risk: "High", recurring: false, likelihood: 0.15,
    symptom: "Stuck float, unplugged, tripped breaker, dead pump", notes: "Porter County basements. Float and power issues are yours.",
  },
  {
    rank: 129, category: "Smart Home & Security", issue: "Keypad code management or rekeying",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.15,
    symptom: "Codes for guests, contractors, departed housekeepers", notes: "Recurring administrative service. Verify Indiana locksmith rules before rekeying for a fee.",
  },
  {
    rank: 130, category: "Smart Home & Security", issue: "Smart lock won't align with strike",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.15,
    symptom: "Deadbolt binding from door or frame movement", notes: "This is a door adjustment problem, not an electronics problem.",
  },
  {
    rank: 131, category: "Appliances", issue: "Electric dryer no heat",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Medium", recurring: false, likelihood: 0.14,
    symptom: "Blown thermal fuse or failed heating element", notes: "Fuse usually blows BECAUSE the vent is blocked - fix both.",
  },
  {
    rank: 132, category: "Electrical", issue: "Hardwired smoke detector end of life",
    scope: "grey", hardStop: false, license: "Local Electrical if hardwired",
    risk: "Low", recurring: false, likelihood: 0.14,
    symptom: "Interconnected set chirping; 10-year sealed units", notes: "Battery swap fine. Replacing a hardwired unit is licensed.",
  },
  {
    rank: 133, category: "HVAC", issue: "Failed run / start capacitor",
    scope: "grey", hardStop: false, license: "Local HVAC (verify)",
    risk: "Medium", recurring: false, likelihood: 0.14,
    symptom: "Condenser hums but fan won't spin", notes: "Common handyman fix in practice; stored charge is a shock hazard.",
  },
  {
    rank: 134, category: "Home Maintenance", issue: "Attic insulation insufficient or displaced",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Medium", recurring: false, likelihood: 0.14,
    symptom: "High bills, ice dams, uneven temperatures", notes: "Diagnosis and top-up. Good energy-audit tie-in.",
  },
  {
    rank: 135, category: "Home Maintenance", issue: "Siding loose or damaged",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Medium", recurring: false, likelihood: 0.14,
    symptom: "Wind, impact, fastener failure", notes: "Small-area repair; large replacement is a referral.",
  },
  {
    rank: 136, category: "Smart Home & Security", issue: "Alarm system false alarms",
    scope: "partial", hardStop: false, license: "None (verify alarm rules)",
    risk: "Low", recurring: false, likelihood: 0.14,
    symptom: "Faulty sensor, pets, misconfigured zone", notes: "Some states license alarm work. Verify Indiana and Porter County.",
  },
  {
    rank: 137, category: "Smart Home & Security", issue: "Doorbell camera poor battery life",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.14,
    symptom: "Too many motion events, cold weather, weak Wi-Fi", notes: "Usually solved by tuning motion zones.",
  },
  {
    rank: 138, category: "Smart Home & Security", issue: "Motion sensor false triggers",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.14,
    symptom: "Pets, headlights, moving branches, heat sources", notes: "Sensitivity and zone tuning.",
  },
  {
    rank: 139, category: "HVAC", issue: "Dirty flame sensor (furnace no heat)",
    scope: "out_of_scope", hardStop: true, license: "Local HVAC (gas)",
    risk: "High", recurring: false, likelihood: 0.13,
    symptom: "Furnace lights then shuts down after seconds", notes: "HARD STOP - gas burner compartment despite being a 5-minute fix.",
  },
  {
    rank: 140, category: "Appliances", issue: "Dryer loud noise or squealing",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.12,
    symptom: "Worn drum rollers, idler pulley, or belt", notes: "Straightforward parts job, fully unregulated.",
  },
  {
    rank: 141, category: "HVAC", issue: "Blower door safety switch not engaged",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.12,
    symptom: "Panel loose after a filter change; unit won't start", notes: "Common after a DIY filter swap.",
  },
  {
    rank: 142, category: "HVAC", issue: "Low refrigerant / refrigerant leak",
    scope: "out_of_scope", hardStop: false, license: "EPA 608 + Local HVAC",
    risk: "High", recurring: false, likelihood: 0.12,
    symptom: "Warm air, ice on line set, long run times", notes: "Federal EPA 608 required. Non-negotiable.",
  },
  {
    rank: 143, category: "Home Maintenance", issue: "Ice dams",
    scope: "partial", hardStop: false, license: "None",
    risk: "High", recurring: false, likelihood: 0.12,
    symptom: "Ice ridge at eave, water backing under shingles", notes: "Seasonal. Address ventilation and insulation, not just the ice.",
  },
  {
    rank: 144, category: "Home Maintenance", issue: "Soffit or fascia damage",
    scope: "partial", hardStop: false, license: "None",
    risk: "Medium (ladder)", recurring: false, likelihood: 0.12,
    symptom: "Rot, animal entry, wind damage", notes: "Often discovered during gutter work - natural upsell.",
  },
  {
    rank: 145, category: "Internet", issue: "Loose or corroded coax / Ethernet connector",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.12,
    symptom: "Intermittent drops, degraded splitter, damaged jack", notes: "Low voltage - fully yours.",
  },
  {
    rank: 146, category: "Plumbing", issue: "Leaking supply stop / angle valve",
    scope: "out_of_scope", hardStop: true, license: "State Plumbing",
    risk: "High", recurring: false, likelihood: 0.12,
    symptom: "Drip at the shutoff behind toilet or under sink", notes: "HARD STOP - tightening a corroded stop shears it and floods the house.",
  },
  {
    rank: 147, category: "Plumbing", issue: "Water hammer / banging pipes",
    scope: "out_of_scope", hardStop: false, license: "State Plumbing",
    risk: "Low", recurring: false, likelihood: 0.12,
    symptom: "Loud knock when a valve closes", notes: "Requires arrestor install. Diagnose and refer.",
  },
  {
    rank: 148, category: "Recurring / Subscription", issue: "Water softener service or resin replacement",
    scope: "out_of_scope", hardStop: false, license: "State Plumbing",
    risk: "Medium", recurring: true, likelihood: 0.12,
    symptom: "Every several years, or on failure", notes: "Salt refill is yours. Servicing the unit connects to the supply system - refer.",
  },
  {
    rank: 149, category: "Smart Home & Security", issue: "Garage door smart controller setup",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.12,
    symptom: "MyQ or similar not pairing or reporting wrong state", notes: "Fully yours.",
  },
  {
    rank: 150, category: "Smart Home & Security", issue: "Guest or family app access management",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.12,
    symptom: "Family members can't access cameras or locks", notes: "Ongoing service opportunity.",
  },
  {
    rank: 151, category: "Smart Home & Security", issue: "Hub failure (SmartThings, Hubitat, Alexa, Google)",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.12,
    symptom: "Whole system unresponsive after hub issue", notes: "Fully yours.",
  },
  {
    rank: 152, category: "Smart Home & Security", issue: "Smart smoke or CO detector offline",
    scope: "partial", hardStop: false, license: "None if battery / Local if hardwired",
    risk: "Low", recurring: false, likelihood: 0.12,
    symptom: "Lost Wi-Fi, needs reconnection after router change", notes: "Battery units yours. Hardwired replacement is licensed.",
  },
  {
    rank: 153, category: "Smart Home & Security", issue: "Water leak sensor placement and setup",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.12,
    symptom: "Sensors unplaced, untested, or not alerting", notes: "Excellent preventive upsell given your plumbing exposure.",
  },
  {
    rank: 154, category: "Appliances", issue: "Dishwasher leaking",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Medium", recurring: false, likelihood: 0.1,
    symptom: "Failed door gasket, overfilling, loose hose clamp", notes: "Yours unless the fix moves to the supply line.",
  },
  {
    rank: 155, category: "Appliances", issue: "Gas range burner won't light",
    scope: "partial", hardStop: true, license: "Local / gas for valve",
    risk: "Medium", recurring: false, likelihood: 0.1,
    symptom: "Clogged port, failed igniter, or gas valve", notes: "Cleaning a port is fine. Anything at the valve is a hard stop.",
  },
  {
    rank: 156, category: "Electrical", issue: "AFCI nuisance tripping",
    scope: "partial", hardStop: false, license: "None to identify",
    risk: "Medium", recurring: false, likelihood: 0.1,
    symptom: "Breaker trips when a specific appliance runs", notes: "Identify the offending load. Breaker work is licensed.",
  },
  {
    rank: 157, category: "Home Maintenance", issue: "Crawlspace vapor barrier displaced",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.1,
    symptom: "Exposed soil, moisture, musty odor", notes: "Straightforward but unpleasant - price accordingly.",
  },
  {
    rank: 158, category: "Home Maintenance", issue: "Garage door off track",
    scope: "partial", hardStop: false, license: "None",
    risk: "High", recurring: false, likelihood: 0.1,
    symptom: "Roller jumped track, panel binding", notes: "Only if springs are not involved. Otherwise refer.",
  },
  {
    rank: 159, category: "Internet", issue: "No wired drop where one is needed",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.1,
    symptom: "Office or TV location needs hardwired Ethernet", notes: "Low-voltage cabling. Solid upsell.",
  },
  {
    rank: 160, category: "Phone", issue: "No dial tone",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.1,
    symptom: "Fault inside wiring or on the telco side", notes: "Isolate at the NID. Carrier-side repairs are free.",
  },
  {
    rank: 161, category: "Plumbing", issue: "Loose or rocking toilet",
    scope: "out_of_scope", hardStop: false, license: "State Plumbing",
    risk: "Medium", recurring: false, likelihood: 0.1,
    symptom: "Failed wax ring, loose closet bolts", notes: "Pulling a toilet is clearly regulated work.",
  },
  {
    rank: 162, category: "Smart Home & Security", issue: "Camera or router privacy audit",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: true, likelihood: 0.1,
    symptom: "Default passwords, open ports, stale firmware", notes: "Genuinely valuable annual review.",
  },
  {
    rank: 163, category: "Smart Home & Security", issue: "PoE camera has no power",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.1,
    symptom: "Failed injector, switch port, or damaged cable", notes: "Low voltage - fully yours.",
  },
  {
    rank: 164, category: "Home Maintenance", issue: "Basement wall crack or water intrusion",
    scope: "out_of_scope", hardStop: false, license: "None (specialty)",
    risk: "Medium", recurring: false, likelihood: 0.09,
    symptom: "Seepage at cove joint or visible crack", notes: "Diagnose and refer. Waterproofing warranties matter to customers.",
  },
  {
    rank: 165, category: "Home Maintenance", issue: "Chimney or flashing leak",
    scope: "out_of_scope", hardStop: false, license: "None state / verify local",
    risk: "High", recurring: false, likelihood: 0.09,
    symptom: "Water intrusion at chimney, valley, or penetration", notes: "Diagnose and refer to a roofer.",
  },
  {
    rank: 166, category: "Plumbing", issue: "Main line backup (multiple fixtures)",
    scope: "out_of_scope", hardStop: false, license: "State Plumbing",
    risk: "High", recurring: false, likelihood: 0.09,
    symptom: "Toilets and tubs backing up simultaneously", notes: "Refer. Often roots or a collapsed line.",
  },
  {
    rank: 167, category: "Smart Home & Security", issue: "NVR or DVR not recording",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.09,
    symptom: "Full drive, failed drive, wrong schedule", notes: "Fully yours.",
  },
  {
    rank: 168, category: "Smart Home & Security", issue: "New camera cable run needed",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.09,
    symptom: "Adding a camera where no wiring exists", notes: "Low-voltage cabling. Strong margin.",
  },
  {
    rank: 169, category: "Smart Home & Security", issue: "Smart switch or dimmer installation",
    scope: "out_of_scope", hardStop: false, license: "Local Electrical",
    risk: "Low", recurring: false, likelihood: 0.09,
    symptom: "Homeowner bought smart switches, needs install", notes: "Line voltage. This is licensed work despite being 'smart home'.",
  },
  {
    rank: 170, category: "Appliances", issue: "Microwave not heating",
    scope: "out_of_scope", hardStop: true, license: "None - but do not open",
    risk: "CRITICAL", recurring: false, likelihood: 0.08,
    symptom: "Failed magnetron, diode, or capacitor", notes: "HARD STOP - HV capacitor holds a lethal charge when unplugged.",
  },
  {
    rank: 171, category: "Electrical", issue: "Whole house outage",
    scope: "out_of_scope", hardStop: false, license: "Utility (NIPSCO)",
    risk: "Medium", recurring: false, likelihood: 0.08,
    symptom: "No power anywhere", notes: "Determine utility side vs main breaker, then call it in.",
  },
  {
    rank: 172, category: "HVAC", issue: "Disconnected or leaking duct in crawl/attic",
    scope: "grey", hardStop: false, license: "None (verify local)",
    risk: "Medium", recurring: false, likelihood: 0.08,
    symptom: "Room won't heat or cool; visible separated duct", notes: "Reconnect plus mastic is typically unregulated.",
  },
  {
    rank: 173, category: "HVAC", issue: "Thermostat loose wire at baseplate",
    scope: "grey", hardStop: false, license: "None (24V low voltage)",
    risk: "Low", recurring: false, likelihood: 0.08,
    symptom: "Intermittent operation; wire backed out of terminal", notes: "Low voltage generally unregulated - confirm locally.",
  },
  {
    rank: 174, category: "Phone", issue: "Static or noise on the line",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.08,
    symptom: "Bad jack, moisture in NID, failing cordless base", notes: "Fully yours.",
  },
  {
    rank: 175, category: "Phone", issue: "VoIP / ATA setup after switching providers",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.08,
    symptom: "Number ported, house wiring not reconnected", notes: "Common after any provider change.",
  },
  {
    rank: 176, category: "Plumbing", issue: "Hose bib leak or freeze break",
    scope: "out_of_scope", hardStop: false, license: "State Plumbing",
    risk: "Medium", recurring: false, likelihood: 0.08,
    symptom: "Drip at spigot, or water in wall when opened", notes: "Often a burst frost-free sillcock inside the wall.",
  },
  {
    rank: 177, category: "Plumbing", issue: "Sump discharge frozen or blocked",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Medium", recurring: false, likelihood: 0.08,
    symptom: "Pump runs but water doesn't leave", notes: "Clearing an exterior discharge line is outside the foundation.",
  },
  {
    rank: 178, category: "Smart Home & Security", issue: "Alarm panel takeover or self-monitoring switch",
    scope: "partial", hardStop: false, license: "Verify alarm licensing",
    risk: "Low", recurring: false, likelihood: 0.08,
    symptom: "Leaving a monitoring contract, keeping the hardware", notes: "Popular cost-saving request. Verify licensing first.",
  },
  {
    rank: 179, category: "Smart Home & Security", issue: "Smart thermostat not controlling system correctly",
    scope: "partial", hardStop: false, license: "None (24V) - verify",
    risk: "Medium", recurring: false, likelihood: 0.08,
    symptom: "Wrong equipment type configured, staging issues", notes: "Misconfiguration can short-cycle equipment.",
  },
  {
    rank: 180, category: "Smart Home & Security", issue: "Whole-home smart system consultation",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.08,
    symptom: "Homeowner wants a plan before buying hardware", notes: "Consulting revenue with zero parts cost.",
  },
  {
    rank: 181, category: "HVAC", issue: "Failed contactor",
    scope: "grey", hardStop: false, license: "Local HVAC (verify)",
    risk: "Medium", recurring: false, likelihood: 0.07,
    symptom: "Chattering or pitted contacts; unit won't engage", notes: "Same grey zone as the capacitor.",
  },
  {
    rank: 182, category: "HVAC", issue: "Gas valve, pilot, or ignitor failure",
    scope: "out_of_scope", hardStop: true, license: "Local HVAC (gas)",
    risk: "High", recurring: false, likelihood: 0.07,
    symptom: "No ignition, no heat", notes: "HARD STOP - gas train work.",
  },
  {
    rank: 183, category: "Plumbing", issue: "Garbage disposal leaking",
    scope: "out_of_scope", hardStop: false, license: "State Plumbing",
    risk: "Medium", recurring: false, likelihood: 0.07,
    symptom: "Leak at flange, drain elbow, or body", notes: "Drain connections. Refer.",
  },
  {
    rank: 184, category: "Appliances", issue: "Gas dryer no heat",
    scope: "out_of_scope", hardStop: true, license: "Local / gas",
    risk: "High", recurring: false, likelihood: 0.06,
    symptom: "Failed igniter or gas valve coils", notes: "HARD STOP under the no-gas rule.",
  },
  {
    rank: 185, category: "Home Maintenance", issue: "Elevated radon level",
    scope: "out_of_scope", hardStop: false, license: "STATE LICENSE REQUIRED",
    risk: "High", recurring: false, likelihood: 0.06,
    symptom: "Test result above 4.0 pCi/L", notes: "Indiana licenses radon testing AND mitigation for compensation (410 IAC 5.1). Do not test for a fee unlicensed.",
  },
  {
    rank: 186, category: "Phone", issue: "One off-hook phone killing the whole line",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.06,
    symptom: "A single faulty handset disables every extension", notes: "Unplug all, add back one at a time.",
  },
  {
    rank: 187, category: "Plumbing", issue: "Water heater leaking from tank",
    scope: "out_of_scope", hardStop: false, license: "State Plumbing",
    risk: "High", recurring: false, likelihood: 0.06,
    symptom: "Water on the floor around the heater", notes: "Tank failure. Shut off supply and refer same day.",
  },
  {
    rank: 188, category: "HVAC", issue: "Blower motor failure",
    scope: "out_of_scope", hardStop: false, license: "Local HVAC",
    risk: "High", recurring: false, likelihood: 0.05,
    symptom: "No airflow, humming, burning smell", notes: "Diagnose and refer.",
  },
  {
    rank: 189, category: "Home Maintenance", issue: "Garage door spring broken",
    scope: "out_of_scope", hardStop: true, license: "None - but HARD STOP",
    risk: "CRITICAL", recurring: false, likelihood: 0.05,
    symptom: "Loud bang, door will not lift, visible gap in spring", notes: "HARD STOP - torsion springs kill and maim people annually. Refer always.",
  },
  {
    rank: 190, category: "Phone", issue: "Voicemail or answering machine setup",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.05,
    symptom: "Can't retrieve messages or set greeting", notes: "Trivial but genuinely valued by older customers.",
  },
  {
    rank: 191, category: "Plumbing", issue: "Frozen or burst pipe",
    scope: "emergency", hardStop: true, license: "State Plumbing",
    risk: "CRITICAL", recurring: false, likelihood: 0.05,
    symptom: "No water in a cold snap, or active flooding", notes: "Shut off water to stop the loss, then refer. Shutoff is not plumbing work.",
  },
  {
    rank: 192, category: "Electrical", issue: "Half the house dead / lost leg / open neutral",
    scope: "out_of_scope", hardStop: true, license: "Utility or Local Electrical",
    risk: "High", recurring: false, likelihood: 0.04,
    symptom: "Half of circuits out, lights dimming and surging", notes: "HARD STOP - destroys electronics, starts fires. Urgent referral.",
  },
  {
    rank: 193, category: "Phone", issue: "Bad phone jack or wall plate",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.04,
    symptom: "Dead extension in one room", notes: "Low voltage - unregulated.",
  },
  {
    rank: 194, category: "Phone", issue: "Medical alert device setup or range problem",
    scope: "in_scope", hardStop: false, license: "None",
    risk: "Low", recurring: false, likelihood: 0.04,
    symptom: "Pendant out of range of base, or untested", notes: "Builds strong loyalty in senior households.",
  },
  {
    rank: 195, category: "Plumbing", issue: "Well pump or pressure tank problem",
    scope: "out_of_scope", hardStop: false, license: "State Plumbing",
    risk: "High", recurring: false, likelihood: 0.04,
    symptom: "No water, rapid cycling, air spitting from taps", notes: "Relevant in rural Porter County.",
  },
  {
    rank: 196, category: "Appliances", issue: "Refrigerator sealed system failure",
    scope: "out_of_scope", hardStop: false, license: "EPA 608",
    risk: "High", recurring: false, likelihood: 0.03,
    symptom: "Compressor not running, or running constantly", notes: "Sealed refrigerant system. Refer.",
  },
  {
    rank: 197, category: "Electrical", issue: "Obsolete panel (Federal Pacific / Zinsco)",
    scope: "out_of_scope", hardStop: false, license: "Local Electrical",
    risk: "High", recurring: false, likelihood: 0.03,
    symptom: "Known failure-to-trip panels found on inspection", notes: "Identify and refer. Real safety finding.",
  },
  {
    rank: 198, category: "Electrical", issue: "Warm, discolored, or scorched outlet",
    scope: "out_of_scope", hardStop: true, license: "Local Electrical",
    risk: "CRITICAL", recurring: false, likelihood: 0.03,
    symptom: "Burning smell, melted face, scorch marks", notes: "HARD STOP - active fire risk. Kill the breaker, refer.",
  },
  {
    rank: 199, category: "Electrical", issue: "Aluminum branch wiring",
    scope: "out_of_scope", hardStop: false, license: "Local Electrical",
    risk: "High", recurring: false, likelihood: 0.02,
    symptom: "Pre-1975 home; connection overheating risk", notes: "Identify and refer for pigtailing / AlumiConn.",
  },
  {
    rank: 200, category: "HVAC", issue: "Cracked heat exchanger / CO hazard",
    scope: "out_of_scope", hardStop: true, license: "Local HVAC (gas)",
    risk: "CRITICAL", recurring: false, likelihood: 0.02,
    symptom: "CO alarm, soot, flame rollout, headaches", notes: "HARD STOP - evacuate, call NIPSCO. Do not diagnose.",
  },
];
